version: "3.7"

services:
  mobile:
    build:
      context: .
      args:
        - NODE_ENV=development
    environment:
      - NODE_ENV=development
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      - ADB_IP=192.168.1.13
      - REACT_NATIVE_PACKAGER_HOSTNAME=192.168.1.3

    tty: true
    ports:
      - '19006:19006'
      - '19001:19001'
      - '19002:19002'
    volumes:
      - ./mobile:/opt/mobile/app:delegated
      - ./mobile/package.json:/opt/mobile/package.json
      - ./mobile/package-lock.json:/opt/mobile/package-lock.json
      - notused:/opt/mobile/app/node_modules
    healthcheck:
      disable: true

volumes:
  notused: